nodes:
  - http://node1:8000
  - http://node2:8000
  - http://node3:8000

operations:
  - operation: create
    group_name: customers

  - operation: create
    group_name: orders

  - operation: delete
    group_name: customers