apiVersion: batch/v1
kind: Job
metadata:
  name: api-consumer
spec:
  backoffLimit: 3

  template:
    metadata:
      labels:
        app: api-consumer

    spec:
      restartPolicy: Never

      containers:
        - name: api-consumer
          image: api-consumer:latest
          imagePullPolicy: IfNotPresent

          command:
            - python
            - main.py

          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
              readOnly: true

      volumes:
        - name: config
          configMap:
            name: api-consumer-config